// Generated by gencpp from file rs232_msgs/rs232Packet.msg
// DO NOT EDIT!


#ifndef RS232_MSGS_MESSAGE_RS232PACKET_H
#define RS232_MSGS_MESSAGE_RS232PACKET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rs232_msgs
{
template <class ContainerAllocator>
struct rs232Packet_
{
  typedef rs232Packet_<ContainerAllocator> Type;

  rs232Packet_()
    : header()
    , count(0)
    , id(0)
    , len(0)
    , dat()
    , flag(0)
    , time(0)  {
      dat.assign(0);
  }
  rs232Packet_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , count(0)
    , id(0)
    , len(0)
    , dat()
    , flag(0)
    , time(0)  {
  (void)_alloc;
      dat.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _count_type;
  _count_type count;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _len_type;
  _len_type len;

   typedef boost::array<uint8_t, 8>  _dat_type;
  _dat_type dat;

   typedef uint16_t _flag_type;
  _flag_type flag;

   typedef uint32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::rs232_msgs::rs232Packet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rs232_msgs::rs232Packet_<ContainerAllocator> const> ConstPtr;

}; // struct rs232Packet_

typedef ::rs232_msgs::rs232Packet_<std::allocator<void> > rs232Packet;

typedef boost::shared_ptr< ::rs232_msgs::rs232Packet > rs232PacketPtr;
typedef boost::shared_ptr< ::rs232_msgs::rs232Packet const> rs232PacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rs232_msgs::rs232Packet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rs232_msgs::rs232Packet_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rs232_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'rs232_msgs': ['/home/lke/kusv_ke/kusv_ros/src/msgs/rs232_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rs232_msgs::rs232Packet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rs232_msgs::rs232Packet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rs232_msgs::rs232Packet_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8315bda71683b8ece50e17e529eea4c1";
  }

  static const char* value(const ::rs232_msgs::rs232Packet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8315bda71683b8ecULL;
  static const uint64_t static_value2 = 0xe50e17e529eea4c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rs232_msgs/rs232Packet";
  }

  static const char* value(const ::rs232_msgs::rs232Packet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 count\n\
uint32 id\n\
uint8  len\n\
uint8[8]  dat\n\
uint16 flag\n\
uint32 time\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rs232_msgs::rs232Packet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.count);
      stream.next(m.id);
      stream.next(m.len);
      stream.next(m.dat);
      stream.next(m.flag);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rs232Packet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rs232_msgs::rs232Packet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rs232_msgs::rs232Packet_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.count);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.len);
    s << indent << "dat[]" << std::endl;
    for (size_t i = 0; i < v.dat.size(); ++i)
    {
      s << indent << "  dat[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.dat[i]);
    }
    s << indent << "flag: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.flag);
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RS232_MSGS_MESSAGE_RS232PACKET_H
